In [1]:
#Load various imports
import numpy as np
import pandas as pd
import os
import librosa
import librosa.display

In [2]:
def features_extractor(filename):
    audio, sample_rate = librosa.load(filename, res_type='kaiser_fast') 
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    
    return mfccs_scaled_features

In [3]:
path = 'C:\\Users\\91844\\Desktop\\Important\\sound classification project\\FanDataset\\NormalFanNoise\\'

extracted_features=[]
for file in os.listdir(path):
    class_label='NormalFan'
    data=features_extractor(path+file)
    extracted_features.append([data,class_label])

In [4]:
df1=pd.DataFrame(extracted_features,columns=['feature','class'])
df1.head()

feature      class
0  [-184.08725, 190.90364, -6.5472474, 69.83528, ...  NormalFan
1  [-188.95596, 184.57324, -5.796834, 69.49344, -...  NormalFan
2  [-187.72867, 227.37573, 1.7841598, 35.303238, ...  NormalFan
3  [-205.62836, 199.65625, 16.706049, 50.15475, -...  NormalFan
4  [-172.0737, 230.81796, -3.084025, 36.8795, -16...  NormalFan

In [5]:
df1.to_csv("NormalFan.csv")

In [6]:
path = 'C:\\Users\\91844\\Desktop\\Important\\sound classification project\\FanDataset\\faultyfan\\'

extracted_features=[]
for file in os.listdir(path):
    class_label='FaultyFan'
    data=features_extractor(path+file)
    extracted_features.append([data,class_label])

In [7]:
df2=pd.DataFrame(extracted_features,columns=['feature','class'])
df2.head()

feature      class
0  [-93.358574, 143.08846, -24.687855, 87.64721, ...  FaultyFan
1  [-83.99258, 133.55707, -43.555065, 84.07892, -...  FaultyFan
2  [-85.85156, 138.25967, -18.470726, 90.875084, ...  FaultyFan
3  [-84.16158, 128.17197, -36.546913, 96.57094, -...  FaultyFan
4  [-103.80153, 147.52713, -20.799234, 86.50566, ...  FaultyFan

In [8]:
df2.to_csv("FaultyFan.csv")

In [9]:
path = 'C:\\Users\\91844\\Desktop\\Important\\sound classification project\\FanDataset\\WeightedbladesNoise\\'

extracted_features=[]
for file in os.listdir(path):
    class_label='WeightedbladesNoise'
    data=features_extractor(path+file)
    extracted_features.append([data,class_label])

In [10]:
df3=pd.DataFrame(extracted_features,columns=['feature','class'])
df3.head()

feature                class
0  [-172.05176, 178.07889, -2.7258942, 64.90754, ...  WeightedbladesNoise
1  [-131.54875, 141.76346, -46.163578, 86.30664, ...  WeightedbladesNoise
2  [-154.2827, 141.59094, -45.067036, 66.9208, -3...  WeightedbladesNoise
3  [-123.77388, 141.92772, -51.178802, 66.29541, ...  WeightedbladesNoise
4  [-74.84768, 150.31708, -69.574745, 72.87649, -...  WeightedbladesNoise

In [11]:
df3.to_csv("WeightedbladesNoise.csv")

In [12]:
Final_data = pd.concat([df1,df2,df3],ignore_index=True)
Final_data

feature                class
0    [-184.08725, 190.90364, -6.5472474, 69.83528, ...            NormalFan
1    [-188.95596, 184.57324, -5.796834, 69.49344, -...            NormalFan
2    [-187.72867, 227.37573, 1.7841598, 35.303238, ...            NormalFan
3    [-205.62836, 199.65625, 16.706049, 50.15475, -...            NormalFan
4    [-172.0737, 230.81796, -3.084025, 36.8795, -16...            NormalFan
..                                                 ...                  ...
256  [-83.35173, 143.92805, -77.120445, 73.46474, -...  WeightedbladesNoise
257  [-84.10093, 145.62115, -70.71969, 74.50148, -3...  WeightedbladesNoise
258  [-87.92287, 145.3846, -70.38933, 70.88521, -34...  WeightedbladesNoise
259  [-86.80471, 148.24329, -81.79567, 77.111336, -...  WeightedbladesNoise
260  [-89.72744, 143.64076, -72.58681, 73.30572, -3...  WeightedbladesNoise

[261 rows x 2 columns]

In [13]:
Final_data.to_csv("Final Data.csv")

In [14]:
X=np.array(Final_data['feature'].tolist())
y=np.array(Final_data['class'].tolist())

In [15]:
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
y=to_categorical(labelencoder.fit_transform(y))

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=30)

In [17]:
print("X_train shape: ",X_train.shape)
print("X_test shape: ",X_test.shape)
print("y_train shape: ",y_train.shape)

X_train shape:  (182, 40)
X_test shape:  (79, 40)
y_train shape:  (182, 3)


In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten
from tensorflow.keras.optimizers import Adam
from sklearn import metrics

In [19]:
num_labels=y.shape[1]
num_labels

3

In [20]:
model=Sequential()
###first layer
model.add(Dense(100,input_shape=(40,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###second layer
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###third layer
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dropout(0.5))

###final layer
model.add(Dense(num_labels))
model.add(Activation('softmax'))

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               4100      
_________________________________________________________________
activation (Activation)      (None, 100)               0         
_________________________________________________________________
dropout (Dropout)            (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 200)               20200     
_________________________________________________________________
activation_1 (Activation)    (None, 200)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 100)               2

In [22]:
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

In [23]:
from tensorflow.keras.callbacks import ModelCheckpoint
from datetime import datetime 


checkpointer = ModelCheckpoint(filepath='C:\\Users\\91844\\Desktop\\Important\\sound classification project\\Saved models\\audio_classification.hdf5', 
                               verbose=1, save_best_only=True)
start = datetime.now()

model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test), callbacks=[checkpointer], verbose=1)


duration = datetime.now() - start
print("Training completed in time: ", duration)

Epoch 1/100
6/6 [==============================] - 3s 449ms/step - loss: 22.4748 - accuracy: 0.4237 - val_loss: 5.8372 - val_accuracy: 0.4557

Epoch 00001: val_loss improved from inf to 5.83715, saving model to C:\Users\91844\Desktop\Important\sound classification project\Saved models\audio_classification.hdf5
Epoch 2/100
6/6 [==============================] - 0s 12ms/step - loss: 18.8697 - accuracy: 0.3923 - val_loss: 2.8121 - val_accuracy: 0.5443

Epoch 00002: val_loss improved from 5.83715 to 2.81213, saving model to C:\Users\91844\Desktop\Important\sound classification project\Saved models\audio_classification.hdf5
Epoch 3/100
6/6 [==============================] - 0s 12ms/step - loss: 15.2281 - accuracy: 0.4279 - val_loss: 1.1763 - val_accuracy: 0.7089

Epoch 00003: val_loss improved from 2.81213 to 1.17632, saving model to C:\Users\91844\Desktop\Important\sound classification project\Saved models\audio_classification.hdf5
Epoch 4/100
6/6 [==============================] - 0s 11ms

6/6 [==============================] - 0s 15ms/step - loss: 0.7666 - accuracy: 0.7927 - val_loss: 0.1191 - val_accuracy: 1.0000

Epoch 00033: val_loss improved from 0.13280 to 0.11909, saving model to C:\Users\91844\Desktop\Important\sound classification project\Saved models\audio_classification.hdf5
Epoch 34/100
6/6 [==============================] - 0s 13ms/step - loss: 0.8670 - accuracy: 0.8165 - val_loss: 0.1156 - val_accuracy: 1.0000

Epoch 00034: val_loss improved from 0.11909 to 0.11556, saving model to C:\Users\91844\Desktop\Important\sound classification project\Saved models\audio_classification.hdf5
Epoch 35/100
6/6 [==============================] - 0s 10ms/step - loss: 0.6791 - accuracy: 0.8070 - val_loss: 0.1221 - val_accuracy: 1.0000

Epoch 00035: val_loss did not improve from 0.11556
Epoch 36/100
6/6 [==============================] - 0s 11ms/step - loss: 0.7653 - accuracy: 0.7688 - val_loss: 0.1233 - val_accuracy: 0.9873

Epoch 00036: val_loss did not improve from 0.115

Epoch 61/100
6/6 [==============================] - 0s 11ms/step - loss: 0.3059 - accuracy: 0.8997 - val_loss: 0.0438 - val_accuracy: 1.0000

Epoch 00061: val_loss improved from 0.04633 to 0.04378, saving model to C:\Users\91844\Desktop\Important\sound classification project\Saved models\audio_classification.hdf5
Epoch 62/100
6/6 [==============================] - 0s 11ms/step - loss: 0.2843 - accuracy: 0.9237 - val_loss: 0.0456 - val_accuracy: 1.0000

Epoch 00062: val_loss did not improve from 0.04378
Epoch 63/100
6/6 [==============================] - 0s 11ms/step - loss: 0.2676 - accuracy: 0.8896 - val_loss: 0.0479 - val_accuracy: 1.0000

Epoch 00063: val_loss did not improve from 0.04378
Epoch 64/100
6/6 [==============================] - 0s 11ms/step - loss: 0.4300 - accuracy: 0.9181 - val_loss: 0.0483 - val_accuracy: 1.0000

Epoch 00064: val_loss did not improve from 0.04378
Epoch 65/100
6/6 [==============================] - 0s 20ms/step - loss: 0.2379 - accuracy: 0.9018 - val_l

6/6 [==============================] - 0s 12ms/step - loss: 0.2022 - accuracy: 0.9561 - val_loss: 0.0204 - val_accuracy: 1.0000

Epoch 00091: val_loss improved from 0.02111 to 0.02042, saving model to C:\Users\91844\Desktop\Important\sound classification project\Saved models\audio_classification.hdf5
Epoch 92/100
6/6 [==============================] - 0s 15ms/step - loss: 0.1206 - accuracy: 0.9660 - val_loss: 0.0201 - val_accuracy: 1.0000

Epoch 00092: val_loss improved from 0.02042 to 0.02014, saving model to C:\Users\91844\Desktop\Important\sound classification project\Saved models\audio_classification.hdf5
Epoch 93/100
6/6 [==============================] - 0s 14ms/step - loss: 0.2356 - accuracy: 0.9009 - val_loss: 0.0198 - val_accuracy: 1.0000

Epoch 00093: val_loss improved from 0.02014 to 0.01982, saving model to C:\Users\91844\Desktop\Important\sound classification project\Saved models\audio_classification.hdf5
Epoch 94/100
6/6 [==============================] - 0s 15ms/step - l

In [24]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])

1.0


In [25]:
y_test = np.argmax(y_test, axis=1)
y_test

array([2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 2, 2, 1, 0,
       1, 0, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 0, 2, 1, 2, 1, 0, 0, 2, 0, 1,
       1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 0, 2, 0, 1, 0, 1, 0, 1, 1, 1, 2, 1,
       1, 0, 2, 1, 0, 0, 0, 0, 1, 2, 1, 2, 0], dtype=int64)

In [26]:
prediction=model.predict_classes(X_test)
prediction

C:\Users\91844\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 2, 2, 1, 0,
       1, 0, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 0, 2, 1, 2, 1, 0, 0, 2, 0, 1,
       1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 0, 2, 0, 1, 0, 1, 0, 1, 1, 1, 2, 1,
       1, 0, 2, 1, 0, 0, 0, 0, 1, 2, 1, 2, 0], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,prediction)

array([[20,  0,  0],
       [ 0, 36,  0],
       [ 0,  0, 23]], dtype=int64)

In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        36
           2       1.00      1.00      1.00        23

    accuracy                           1.00        79
   macro avg       1.00      1.00      1.00        79
weighted avg       1.00      1.00      1.00        79



In [29]:
filename="C:\\Users\\91844\\Desktop\\Important\\sound classification project\\NormalFan.wav"
audio, sample_rate = librosa.load(filename, res_type='kaiser_fast') 
mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)

print(mfccs_scaled_features)
mfccs_scaled_features=mfccs_scaled_features.reshape(1,-1)
print(mfccs_scaled_features)
print(mfccs_scaled_features.shape)
predicted_label=model.predict_classes(mfccs_scaled_features)
print(predicted_label)
prediction_class = labelencoder.inverse_transform(predicted_label) 
prediction_class

[-2.0293791e+02  2.2071227e+02  1.5825939e+01  3.1833752e+01
  2.3305397e+00  1.2287267e+01  8.0954771e+00 -2.9111354e+00
  7.6514089e-01 -1.8769060e+00  4.0891919e+00 -3.6546390e+00
  1.2687507e+00 -2.6300827e-01 -2.3938851e+00 -1.2563185e-01
 -2.0397182e+00  4.3917480e-01 -3.0210164e+00 -5.4063338e-01
 -1.1667554e+00 -2.0433290e+00 -2.0752246e+00 -2.7953534e+00
 -1.2671468e+00 -2.9746258e+00 -1.1783874e+00 -2.7860906e+00
 -1.5987916e+00 -1.8916085e+00 -2.7459683e+00 -8.2427406e-01
 -3.3708594e+00 -9.1791791e-01 -2.2013009e+00 -2.1560917e+00
 -1.1892284e+00 -2.8277683e+00 -8.8909358e-01 -2.8971841e+00]
[[-2.0293791e+02  2.2071227e+02  1.5825939e+01  3.1833752e+01
   2.3305397e+00  1.2287267e+01  8.0954771e+00 -2.9111354e+00
   7.6514089e-01 -1.8769060e+00  4.0891919e+00 -3.6546390e+00
   1.2687507e+00 -2.6300827e-01 -2.3938851e+00 -1.2563185e-01
  -2.0397182e+00  4.3917480e-01 -3.0210164e+00 -5.4063338e-01
  -1.1667554e+00 -2.0433290e+00 -2.0752246e+00 -2.7953534e+00
  -1.2671468e+00 

array(['NormalFan'], dtype='<U19')